// <auto-generated />
namespace EfMvcApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class aaa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aaa));
        
        string IMigrationMetadata.Id
        {
            get { return "201401111036214_aaa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
